name: sdk

on:
  workflow_dispatch:
#   push:
  # pull_request:

env:
  TAG_NAME: "dev"
  LLVM_VERSION: "15.0.6"

permissions:
  contents: write

jobs:

  build-for-windows:
    name: ${{ matrix.job.target }} (${{ matrix.job.os }})
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
          - { target: x86_64-pc-windows-msvc, os: windows-2019, arch: x86_64 }
          - { target: i686-pc-windows-msvc, os: windows-2019, arch: i686 }
    steps:

    - uses: actions/checkout@v2
    - uses: ilammy/msvc-dev-cmd@v1

    - name: Source
      run: |
        git clone --depth=1 https://github.com/21pages/externals.git
    
    - name: Build
      working-directory: externals
      run: |
        cd Video_Codec_SDK_11.1.5
        cmake -B build
        cmake --build build -j4 --config Release
        cd ..
        cd AMF_v1.4.29
        cmake -B build
        cmake --build build -j4 --config Release
        cd ..
        cd libvpl_v2023.4.0
        cmake -B build
        cmake --build build -j4 --config Release
        cd ..

        New-Item -ItemType Directory -Path sdk_windows_${{ matrix.job.arch }}
        Copy-Item -Path Video_Codec_SDK_11.1.5/build/Release/video_codec_sdk.lib -Destination sdk_windows_${{ matrix.job.arch }} -Force
        Copy-Item -Path AMF_v1.4.29/build/Release/amf.lib -Destination sdk_windows_${{ matrix.job.arch }} -Force
        Copy-Item -Path libvpl_v2023.4.0/build/Release/vpl.lib -Destination sdk_windows_${{ matrix.job.arch }} -Force
    
    - name: Create Archive
      uses: thedoctor0/zip-release@0.7.1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        type: 'zip'
        filename: './sdk_windows_${{ matrix.job.arch }}.zip'
        path: 'externals/sdk_windows_${{ matrix.job.arch }}'
    
    - name: Publish
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        prerelease: true
        tag_name: ${{ env.TAG_NAME }}
        files: | 
          ./sdk_windows_${{ matrix.job.arch }}.zip

  